name: Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate deploy
        run: |
          echo "Deploying ${GITHUB_REPOSITORY} ${GITHUB_REF_NAME}..."
          sleep 12
          echo "done"
          exit 0
